name: CI

on:
  push:
    branches: [master]

env:
  TZ: UTC

jobs:
  release:
    outputs:
      tag: ${{ steps.new_tag.outputs.next_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate tag for new version
        id: new_tag
        uses: haya14busa/action-bumpr@v1
        with:
          default_bump_level: patch
          dry_run: false

  build:
    runs-on: ubuntu-latest
    needs: [ release ]
    strategy:
      matrix:
        service:
          - name: app
            directory: packages/front
          - name: api
            directory: packages/api
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.service.directory }}/Dockerfile
          push: true
          tags: |
            ghcr.io/marmorag/supateam-${{ matrix.service.name }}:${{ needs.release.outputs.tag }}
            ghcr.io/marmorag/supateam-${{ matrix.service.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max