name: CI

on:
  push: {}

env:
  TZ: UTC

jobs:
  tests:
    strategy:
      matrix:
        go: [1.18.x]
    runs-on: ubuntu-latest
    services:
      supateam-database-mongo:
        image: mongo:5-focal
        ports:
          - "27017:27017"
        env:
          MONGO_INITDB_ROOT_USERNAME: supateam
          MONGO_INITDB_ROOT_PASSWORD: supateam
          MONGO_INITDB_DATABASE: supateam
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('packages/api/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: make swagger
        shell: bash
        working-directory: packages/api

      - run: make test
        shell: bash
        working-directory: packages/api

  release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [tests]
    outputs:
      tag: ${{ steps.new_tag.outputs.next_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate tag for new version
        id: new_tag
        uses: haya14busa/action-bumpr@v1
        with:
          default_bump_level: patch
          dry_run: false

  build:
    runs-on: ubuntu-latest
    needs: [ release ]
    strategy:
      matrix:
        service:
          - name: app
            directory: packages/front
          - name: api
            directory: packages/api
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.service.directory }}/Dockerfile
          push: true
          tags: |
            ghcr.io/marmorag/supateam-${{ matrix.service.name }}:${{ needs.release.outputs.tag }}
            ghcr.io/marmorag/supateam-${{ matrix.service.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  rollout:
    runs-on: ubuntu-latest
    needs: [ release, build ]
    steps:
      - name: rollout new version
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GHCR_TOKEN }}
          repository: marmorag/System
          event-type: rollout
          client-payload: '{"application": "supateam", "service": "*", "environment": "prod", "tag": "${{ needs.release.outputs.tag }}"}'